#+TITLE: 30 Days of Persian
#+ORGA_PUBLISH_KEYWORD: PUBLISHED
#+TODO: DRAFT | PUBLISHED
#+FILETAGS: persian
* PUBLISHED Overview: 30 Days of Persian Challenge
CLOSED: [2019-09-21 Sat 16:26]
#+HTML: <div class="persian callout">
سلام!
#+HTML: </div>
** Hello there!
I'm going to start learning Persian over the next 30 days or so (I'll allow
myself the odd cheat day).

I'll be using [[https://www.chaiandconversation.com/][Chai & Conversation]] as my main resource. Since I'm also interested
in learning how to write informal Persian, I'll use Google Translate and some
other Internet resources to help me transcribe what I hear.
** Why Persian?
I've studied Standard Arabic on my own for about a year. It's been a lot of fun
but I've met a lot more Iranians than Arabic-speakers in my day-to-day life, so
I've decided to switch over. I've also dated a few Persians. :sweat_smile:

My prior exposure to Arabic means I'm already comfy with the Persian writing
system. As a bonus, Persian borrows a lot of vocabulary from Arabic, which makes
things easier.
** Why a 30 Day Challenge?
I want to cultivate a regular study habit, and I'm curious to see if this
approach gets me into the mood.
* PUBLISHED 30 Days of Persian: Day One
CLOSED: [2019-09-22 Sun 22:31]
- [[https://www.chaiandconversation.com/podcast/how-greet-people-and-ask-how-theyre-doing][How to Greet People and Ask How They're Doing]]
- I've already studied this, so it's revision.
** Phrases
- سلام ::
  hello
- چطوری ::
  how are you?
- سلام، چطوری! ::
  hi, how are you?
- خوبم ::
  I'm well
- مرسی ::
  thank you
  - Persians will actually pronounce the =/r/= as a uvular frictive to closer
    mimic the French pronunciation.
- خیلی خوبم ::
  I'm very well
  - خیلی... ::
    very...
  - خیلی خوب ::
    very good
- عالی ::
  (I'm) great
- خوب نیستم ::
  I'm not good
- بد نیستم ::
  I'm not bad
- من ::
  me/I
  - 1st person subject or object pronoun
** Conversation 1
- لیلا: سلام مت، چطوری؟
- مت: خوبم مرسی. چطوری؟
- لیلا: خوبم مرسی.
** Conversation 2
- لیلا: سلام مت. چطوری؟
- مت: بد نیستم. چطوری؟
- لیلا: من؟ خوبم مرسی.
** Conversation 3
- لیلا: سلام مت. چطوری؟
- مت: عالی!
** Notes
- The Wikipedia page on [[https://en.wikipedia.org/wiki/Persian_phonology][Persian Phonology]] is a good reference for consonant
  values
- See also [[https://en.wikipedia.org/wiki/Classical_Arabic#Phonology][Classical Arabic#Phonology]] for comparison
- Persian pronunciation does not distinguish several sounds that are represented by different letters in the script.
  - E.g. ط ⟨tˠ⟩ and ت ⟨t⟩ have different values in Standard Arabic, but are both ⟨t⟩ in Persian
* DRAFT 30 Days of Persian: Day Two
